name: glamod_QC_dev
channels:
  - conda-mo-internal
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=1.0.0
  - asttokens=3.0.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.5
  - aws-c-http=0.10.4
  - aws-c-io=0.21.2
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.6
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.33.1
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.0
  - azure-identity-cpp=1.12.0
  - azure-storage-blobs-cpp=12.14.0
  - azure-storage-common-cpp=12.10.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.17.0
  - blosc=1.21.6
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brotli=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - cartopy=0.25.0
  - certifi=2025.8.3
  - cf-units=3.3.0
  - cffi=1.17.1
  - cftime=1.6.4
  - charset-normalizer=3.4.3
  - click=8.2.1
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - contourpy=1.3.3
  - coverage=7.2.2
  - cycler=0.12.1
  - dask-core=2025.7.0
  - decorator=5.2.1
  - docutils=0.21.2
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - fonttools=4.59.0
  - freetype=2.13.3
  - fsspec=2025.7.0
  - geos=3.13.1
  - gflags=2.2.2
  - glog=0.7.1
  - h2=4.2.0
  - hdf4=4.2.15
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.10
  - imagesize=1.4.1
  - importlib-metadata=8.7.0
  - iniconfig=2.0.0
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - iris=3.6.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250512.1
  - libaec=1.1.4
  - libarrow-acero=21.0.0
  - libarrow-compute=21.0.0
  - libarrow-dataset=21.0.0
  - libarrow-substrait=21.0.0
  - libarrow=21.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.14.1
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype6=2.13.3
  - libfreetype=2.13.3
  - libgcc-ng=15.1.0
  - libgcc=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgfortran=15.1.0
  - libgomp=15.1.0
  - libgoogle-cloud-storage=2.39.0
  - libgoogle-cloud=2.39.0
  - libgrpc=1.73.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma-devel=5.8.1
  - liblzma=5.8.1
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopenblas=0.3.25
  - libopentelemetry-cpp-headers=1.21.0
  - libopentelemetry-cpp=1.21.0
  - libparquet=21.0.0
  - libpng=1.6.50
  - libprotobuf=6.31.1
  - libre2-11=2025.07.22
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx-ng=15.1.0
  - libstdcxx=15.1.0
  - libthrift=0.22.0
  - libtiff=4.7.0
  - libudunits2=2.2.28
  - libutf8proc=2.10.0
  - libuuid=2.38.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libzip=1.11.2
  - libzlib=1.3.1
  - locket=1.0.0
  - lz4-c=1.10.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.5
  - matplotlib-inline=0.1.7
  - munkres=1.1.4
  - ncurses=6.5
  - netcdf4=1.7.2
  - nlohmann_json=3.12.0
  - numpy=1.25.0
  - openjpeg=2.5.3
  - openssl=3.5.2
  - orc=2.2.0
  - packaging=25.0
  - pandas=1.5.3
  - parso=0.8.4
  - partd=1.4.2
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pluggy=1.6.0
  - proj=9.6.2
  - prometheus-cpp=1.3.0
  - prompt-toolkit=3.0.51
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow-core=21.0.0
  - pyarrow=21.0.0
  - pycparser=2.22
  - pyflakes=3.0.1
  - pygments=2.19.2
  - pyparsing=3.2.3
  - pyproj=3.7.1
  - pyshp=3.0.0
  - pysocks=1.7.1
  - pytest=7.4.0
  - python-dateutil=2.9.0.post0
  - python-xxhash=3.5.0
  - python=3.11.4
  - python_abi=3.11
  - pytz=2025.2
  - pyyaml=6.0.2
  - qhull=2020.2
  - re2=2025.07.22
  - readline=8.2
  - requests=2.32.4
  - reverse_geocoder=1.5.1
  - roman-numerals-py=3.1.0
  - s2n=1.5.23
  - scipy=1.9.3
  - scitools-iris=3.6.1
  - setuptools=80.9.0
  - shapely=2.1.1
  - six=1.17.0
  - snappy=1.2.2
  - snowballstemmer=3.0.1
  - sphinx-design==0.6.1
  - sphinx=8.2.3
  - sphinx_rtd_theme=3.0.1
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jquery=4.1
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - sqlite=3.50.4
  - stack_data=0.6.3
  - tk=8.6.13
  - tomli=2.2.1
  - toolz=1.0.0
  - traitlets=5.14.3
  - typing_extensions=4.14.1
  - tzdata=2025b
  - udunits2=2.2.28
  - unicodedata2=16.0.0
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xxhash=0.8.3
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - xz=5.8.1
  - yaml=0.2.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7

