name: glamod_QC_dev
channels:
  - conda-forge
dependencies:
  - coverage=7.2.2
  - ipython[version='>=8.12']
  - numpy=1.25.0
  - pandas=1.5.3
  - pyarrow
  - pyflakes=3.0.1
  - pytest=7.4.0
  - python=3.11.4
  - reverse_geocoder=1.5.1
  - scipy=1.9.3
  - scitools-iris=3.6.1
  - sphinx
  - sphinx_rtd_theme

